[telegram]
token = ""
workers = 4
persistence = "persistence/data.pickle" # keep empty to disable percistency of temporary data (chat_data/user_data)
show_commands = false # show commands popup when "/" is typed
admins = [23646077]
exit_unknown_groups = true # exit groups when added by non-admin/non-whitelisted users
voice_max_size = 10000000 # 10 mb
silence_exceptions_private = false
silence_exceptions_group = true

[google]
service_account_json = ""
punctuation = false # transcribe with punctuation

[misc]
remove_downloaded_files = true
keep_files_on_error = true # do not delete file that generate an exception/receive an empty response

[database]
engine_string = "sqlite:///bot.db"
